name: build

on:
  pull_request:
    types: [ opened,synchronize ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          path: my-package
          fetch-tags: true
          fetch-depth: 0
      - name: Check out texmf
        uses: actions/checkout@v4
        with:
          repository: Xerdi/texmf-packaging
          path: texmf
      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
          image: maclotsen/texlive:with-gf
          shell: bash
          options: --rm -i -v ${{ github.workspace }}/texmf:/root/texmf -v ${{ github.workspace }}:/build
          run: |
            git config --global --add safe.directory /build/my-package
            make -C my-package manual
      - name: Archive Documentation
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: ${{ github.workspace }}/my-package/doc
